"""Add Ticket.revision

Revision ID: 2582ef7a7b34
Revises: 6552cefff319
Create Date: 2024-01-10 00:49:29.838825

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2582ef7a7b34'
down_revision: Union[str, None] = '6552cefff319'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Ticket', sa.Column('revision', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('Ticket', 'revision')
    # ### end Alembic commands ###
